# Generated by Django 4.2.5 on 2023-09-28 02:20

from django.db import migrations


def populate_status(apps, schemaeditor):
    entries = {
        "To Do": "An issue for which work has not yet been started",
        "In Progress": "An issue that is actively worked on",
        "Done": "An issue for which work has been completed"
    }
    Status = apps.get_model("issues", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
