# Generated by Django 4.2.5 on 2023-09-28 23:04

from django.db import migrations


def populate_priority(apps, schemaeditor):
    entries = {
        "High": "Stop what you're doing",
        "Medium": "Do this when you get the chance",
        "Low": "It can wait"
    }
    Priority = apps.get_model("issues", "Priority")
    for key, value in entries.items():
        priority_obj = Priority(name=key, description=value)
        priority_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_status'),
    ]

    operations = [
        migrations.RunPython(populate_priority)
    ]
