# Generated by Django 4.2.5 on 2023-09-28 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_priority_issue_priority'),
        ('issues', '0005_auto_20230928_2304'),
    ]

    operations = [
    ]
