# Generated by Django 4.2.5 on 2023-09-28 01:38

from django.db import migrations


def populate_role(apps, schemaeditor):
    entries = {
        "Developer": "A person tasked with completing issues",
        "Scrum Master": "The development team's coach",
        "Product Owner": "A team member who defines tasks",
    }
    Role = apps.get_model("accounts", "Role")
    for key, value in entries.items():
        role_obj = Role(name=key, description=value)
        role_obj.save()


def populate_team(apps, schemaeditor):
    entries = {
        "Alpha": "The A Team",
        "Bravo": "The B Team",
        "Charlie": "The C Team",
        "Delta": "The D Team"
    }
    Team = apps.get_model("accounts", "Team")
    for key, value in entries.items():
        team_obj = Team(name=key, description=value)
        team_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_role),
        migrations.RunPython(populate_team)
    ]
